ALTER TABLE incidents
ADD COLUMN IF NOT EXISTS severity TEXT DEFAULT 'low',
ADD COLUMN IF NOT EXISTS summary TEXT,
ADD COLUMN IF NOT EXISTS deltas JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS forensic_report JSONB DEFAULT '{}'::jsonb;
